### ISSUE TITLE
[Bug]: 把项目里的过期的淘宝镜像源换一下吧

### ISSUE THREAD

**Issue by adcodeday** [Evansy/MallChatWeb#117]
**BUG 描述**
简洁而清晰的描述 bug 内容.

**预期效果**
简洁而清晰的描述你预期的效果.

**信息**

- 系统: [e.g. iOS]
- 系统版本: [e.g. iOS 16.3]
- 浏览器: [e.g. chrome 62]

**Comment by Evansy** [comment]
好的，已处理: 16e7b55adfeda98c540b18ae6e19ad0588fa15ee
