### ISSUE TITLE
[Feature]: 建议把 "点赞" 与 "点踩" 大于0 的时候 , 数量给显示出来

### ISSUE THREAD

**Issue by xxxxue** [Evansy/MallChatWeb#29]
**想法内容**

比如图片中的这样

![image](https://github.com/Evansy/MallChatWeb/assets/32764266/c73d73a3-787a-44cb-9cc5-2e87d4f33097)

**Comment by Evansy** [comment]
目前这个已经实现了哦，不好意思没有及时处理issue
