### ISSUE TITLE
[Feature]:  建议把 消息操作 改为 菜单形式

### ISSUE THREAD

**Issue by xxxxue** [Evansy/MallChatWeb#30]
**想法内容**

效果如图

鼠标悬浮到 消息上 (移动端是点击消息体),  显示 菜单图标按钮
点击后, 展开菜单

![image](https://github.com/Evansy/MallChatWeb/assets/32764266/2b3ac5d7-0c5c-422a-ae6b-816bd2034180)

**Comment by Evansy** [comment]
不好意思😅，这个菜单在讨论计划中，近期就会上线了，没有及时回复万分抱歉。
