### ISSUE TITLE
[Bug]: 加载更多消息后，虚拟列表定位到加载时的那条消息位置有误差。

### ISSUE THREAD

**Issue by xyqfei** [Evansy/MallChatWeb#55]
**BUG 描述**
加载更多消息后，定位到加载时的那条消息位置有误差。

**预期效果**
加载更多消息完成后，消息准确定位到加载时的那条消息

**信息**

- 系统: [iOS]
- 系统版本: [iOS 12.1]
- 浏览器: [chrome 114.0.5735.106（正式版本） (arm64)]

bug视频
https://github.com/Evansy/MallChatWeb/assets/23380976/8deff4f1-e0bb-4494-af7b-3c2c9c2df548

问题初步分析：

https://github.com/Evansy/MallChatWeb/blob/29b8c268e9dce5725d2ce171fd6ecdcb40be1133/src/views/Home/components/ChatList/index.vue#L31-L39

当触顶事件onToTop事件内计算得出的newScrollTop都没有问题，但是
```js
virtualListRef.value.scrollToOffset(newScrollTop)
```
会导致虚拟列表scrollHeight改变，从而使定位出现误差。

以下是验证代码
```js
const onTotop = throttle(async () => {
  const oldScrollTop = virtualListRef.value.getScrollSize()
  await chatStore.loadMore()
  nextTick(() => {
    const scrollHeight1 = virtualListRef.value.getScrollSize()
    console.log(scrollHeight1)
    const newScrollTop = virtualListRef.value.getScrollSize() - oldScrollTop
    virtualListRef.value.scrollToOffset(newScrollTop)
  }).then(() => {
    nextTick(() => {
      setTimeout(() => {
        const scrollHeight2 = virtualListRef.value.getScrollSize()
        console.log(scrollHeight2)
      }, 1000)
    })
  })
}, 1600)```

结果发现 scrollHeight1 和 scrollHeight2 并不相等。

**Comment by Evansy** [comment]
#58 已修复
