### ISSUE TITLE
[Bug]: @指定人后不输入内容后回车，会不显示对应@人的名称

### ISSUE THREAD

**Issue by Babelyj** [Evansy/MallChatWeb#75]
**BUG 描述**
@指定人后不输入内容后回车，会不显示对应@人的名称

**预期效果**
@指定人后可强制要求输入内容，否则不进行发送，或者显示指定人的名称

![image](https://github.com/Evansy/MallChatWeb/assets/45281327/fa674b69-192a-464b-8450-07a32c349a95)
![image](https://github.com/Evansy/MallChatWeb/assets/45281327/989ca025-5054-41c1-9945-6c4e073b93a2)

- 系统: [e.g. iOS]
- 系统版本: [e.g. iOS 16.3]
- 浏览器: [e.g. chrome 62]

**Comment by Evansy** [comment]
已修复
