### ISSUE TITLE
[Bug]: 上传了一个mp3文件，实际被解析为一段语音，预期效果是一个文件。

### ISSUE THREAD

**Issue by xyqfei** [Evansy/MallChatWeb#77]
**BUG 描述**
上传了一个mp3文件，实际被解析为一段语音，
<img width="824" alt="image" src="https://github.com/Evansy/MallChatWeb/assets/23380976/38cf7a6c-56e2-45aa-b948-113822957e1c">

**预期效果**
预期效果是一个可下载的mp3文件

**信息**

- 系统: [iOS]
- 系统版本: [macOS Monterey 12.1]
- 浏览器: [chrome 114.0.5735.198（正式版本） (arm64)]

**Comment by Evansy** [comment]
#79 已修复
