### ISSUE TITLE
[Bug]: url点击无法跳转

### ISSUE THREAD

**Issue by zongzibinbin** [Evansy/MallChatWeb#80]
**BUG 描述**
如果url没有携带http或者https的协议，前端能够识别url，但是无法匹配。

**预期效果**
对于没有协议的url，前端可以根据判断是否含有http，没有默认加上http://前缀，这样即可跳转

**信息**

- 系统: [e.g. iOS]
- 系统版本: [e.g. iOS 16.3]
- 浏览器: [e.g. chrome 62]

**Comment by Evansy** [comment]
#81 已修复
